version: '3'
services:
  backend:
    restart: always
    build: backend/
    ports:
      - "8000:8000"
    networks:
      - AIShield_network
    volumes:
      - ./data:/data
      - ./assets:/assets
      - ./weights:/weights
    container_name: backend

  frontend:
    build: frontend/
    depends_on:
      - backend
    ports: 
      - 8501:8501
    networks:
      - AIShield_network
    container_name: frontend

networks:
  AIShield_network:
    driver: bridge




